include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/l10n/*.dart' # Exclude generated localization files
    - 'build/**' # Exclude build folder

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    # always_use_build_context: true
    avoid_function_literals_in_foreach_calls: true
    avoid_redundant_argument_values: true
    avoid_returning_this: true
    cascade_invocations: true
    close_sinks: true
    constant_identifier_names: true
    control_flow_in_finally: true
    empty_catches: true
    empty_constructor_bodies: true
    implementation_imports: true
    library_prefixes: true
    no_duplicate_case_values: true
    no_logic_in_create_state: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_if_null_operators: true
    prefer_interpolation_to_compose_strings: true
    # prefer_single_quotes: true
    sized_box_for_whitespace: true
    unnecessary_brace_in_string_interps: true
    unnecessary_const: true
    unnecessary_new: true
    unnecessary_null_checks: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_this: true
    use_build_context_synchronously: true
    use_key_in_widget_constructors: true
    use_named_constants: true
    use_super_parameters: true
    use_setters_to_change_properties: true
    sort_child_properties_last: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    secure_pubspec_urls: true
    sort_pub_dependencies: true # This is the import sorting rule

