// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrsz8g3TFqxrvAwLREeKbt0N8P-jgokiM',
    appId: '1:289043922212:web:5a7238cb54e60be33047b1',
    messagingSenderId: '289043922212',
    projectId: 'app-circlechat',
    authDomain: 'app-circlechat.firebaseapp.com',
    storageBucket: 'app-circlechat.firebasestorage.app',
    measurementId: 'G-02L3HCL6TK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEB2wOdnf4GA1VQO-EvbkSVkmSHqfuL5E',
    appId: '1:289043922212:android:2888bf8a407f835f3047b1',
    messagingSenderId: '289043922212',
    projectId: 'app-circlechat',
    storageBucket: 'app-circlechat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvLFik0ZLZZH5a0tctCe8xejVm5aDrGso',
    appId: '1:289043922212:ios:4f8e5ce3ff28c9843047b1',
    messagingSenderId: '289043922212',
    projectId: 'app-circlechat',
    storageBucket: 'app-circlechat.firebasestorage.app',
    iosBundleId: 'com.circlechat.app.circlechatApp',
  );
}
